version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: invoice
      POSTGRES_PASSWORD: invoice123
      POSTGRES_DB: invoice
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@invoice.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
