version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  app-executor:
    docker:
      - image: cimg/node:14.19
    working_directory: ~/repo

aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &restore-cache
    restore_cache:
      keys:
        - app-{{ checksum "package.json" }}
        - app-
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &save-cache
    save_cache:
      paths:
        - node_modules
      key: app-{{ checksum "package.json" }}

jobs:
  build:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - *install-dependencies
      - *save-cache

  linting:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run linting
          command: npm run lint:check

  prettier:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Run prettier check
          command: npm run prettier:check

  unit_tests:
    executor: app-executor
    docker:
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: invoice
          POSTGRES_PASSWORD: invoice123
          POSTGRES_DB: invoice
    steps:
      - checkout
      - *show-current-branch-name
      - *restore-cache
      - run:
          name: Waiting for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run unit tests
          command: npm run test
    environment:
      DATABASE_URL: postgresql://invoice:invoice123@localhost:5432/invoice?schema=public
      POSTGRES_USER: invoice
      POSTGRES_PASSWORD: invoice123
      POSTGRES_DB: invoice

workflows:
  check_and_deploy:
    jobs:
      - build
      - linting:
          requires:
            - build
          filters:
            branches:
              only: main
      - prettier:
          requires:
            - build
          filters:
            branches:
              only: main
      - unit_tests:
          requires:
            - linting
            - prettier
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          force: true
          requires:
            - unit_tests
          filters:
            branches:
              only: main
